version: '3.8'
services:
  postgres:
    image: ${IMAGE_NAME}
    container_name: ${CONTAINER_NAME}
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - "6400:5432"
    volumes:
      - ${CONTAINER_VOLUME}:/var/lib/postgresql/data
    networks:
      - pgsql_net # 新增：指定网络

networks:
  pgsql_net: # 新增：定义网络
